services:
  # 1. Static site for the frontend
  - type: web
    name: frontend
    runtime: static
    rootDir: "."                   # <-- since your `package.json`, `src/`, etc. live at repo root
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://<your-backend-service>.onrender.com"
    routes:
      # Proxy any /products* calls to your backend
      - type: rewrite
        source: /products/(.*)
        destination: https://<your-backend-service>.onrender.com/products/$1
      - type: rewrite
        source: /products
        destination: https://<your-backend-service>.onrender.com/products
      # All other routes serve index.html
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. Web service for the API
  - type: web
    name: backend
    runtime: node
    rootDir: "."                   # <-- same repo root
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: GOLD_API_KEY
        value: $GOLD_API_KEY
